[2025-01-20T13:41:31.407+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T13:41:31.416+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: connection_postgre.create_table manual__2025-01-20T13:41:30.104066+00:00 [queued]>
[2025-01-20T13:41:31.421+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: connection_postgre.create_table manual__2025-01-20T13:41:30.104066+00:00 [queued]>
[2025-01-20T13:41:31.422+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-20T13:41:31.433+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_table> on 2025-01-20 13:41:30.104066+00:00
[2025-01-20T13:41:31.438+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2215) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T13:41:31.440+0000] {standard_task_runner.py:72} INFO - Started process 2219 to run task
[2025-01-20T13:41:31.439+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'connection_postgre', 'create_table', 'manual__2025-01-20T13:41:30.104066+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/postgre.py', '--cfg-path', '/tmp/tmp9o5uk2jf']
[2025-01-20T13:41:31.442+0000] {standard_task_runner.py:105} INFO - Job 156: Subtask create_table
[2025-01-20T13:41:31.473+0000] {task_command.py:467} INFO - Running <TaskInstance: connection_postgre.create_table manual__2025-01-20T13:41:30.104066+00:00 [running]> on host 7854821b9569
[2025-01-20T13:41:31.694+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='connection_postgre' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T13:41:30.104066+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T13:41:30.104066+00:00'
[2025-01-20T13:41:31.695+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T13:41:31.713+0000] {base.py:84} INFO - Retrieving connection 'postgres_connexion'
[2025-01-20T13:41:32.049+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-20T13:41:32.056+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T13:41:32.057+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=connection_postgre, task_id=create_table, run_id=manual__2025-01-20T13:41:30.104066+00:00, execution_date=20250120T134130, start_date=20250120T134131, end_date=20250120T134132
[2025-01-20T13:41:32.097+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-20T13:41:32.110+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T13:41:32.113+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
