[2025-01-22T08:56:12.291+0000] {processor.py:186} INFO - Started process (PID=578) to work on /opt/airflow/dags/b.py
[2025-01-22T08:56:12.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T08:56:12.294+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:56:12.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T08:56:12.309+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:56:12.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T08:56:12.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T08:56:12.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.036 seconds
[2025-01-22T08:56:42.952+0000] {processor.py:186} INFO - Started process (PID=590) to work on /opt/airflow/dags/b.py
[2025-01-22T08:56:42.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T08:56:42.955+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:56:42.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T08:56:42.964+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:56:42.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T08:56:42.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T08:56:42.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.030 seconds
[2025-01-22T08:57:13.674+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/b.py
[2025-01-22T08:57:13.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T08:57:13.676+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:57:13.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T08:57:13.687+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:57:13.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T08:57:13.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T08:57:13.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.029 seconds
[2025-01-22T08:57:44.358+0000] {processor.py:186} INFO - Started process (PID=614) to work on /opt/airflow/dags/b.py
[2025-01-22T08:57:44.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T08:57:44.360+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:57:44.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T08:57:44.373+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:57:44.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T08:57:44.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T08:57:44.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.033 seconds
[2025-01-22T08:58:15.035+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/b.py
[2025-01-22T08:58:15.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T08:58:15.037+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:58:15.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T08:58:15.051+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:58:15.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T08:58:15.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T08:58:15.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.033 seconds
[2025-01-22T08:58:45.656+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/b.py
[2025-01-22T08:58:45.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T08:58:45.659+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:58:45.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T08:58:45.671+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:58:45.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T08:58:45.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T08:58:45.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.035 seconds
[2025-01-22T08:59:16.299+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/b.py
[2025-01-22T08:59:16.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T08:59:16.302+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:59:16.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T08:59:16.314+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:59:16.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T08:59:16.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T08:59:16.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.034 seconds
[2025-01-22T08:59:46.989+0000] {processor.py:186} INFO - Started process (PID=662) to work on /opt/airflow/dags/b.py
[2025-01-22T08:59:46.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T08:59:46.991+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:59:46.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T08:59:46.998+0000] {logging_mixin.py:190} INFO - [2025-01-22T08:59:46.997+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T08:59:46.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T08:59:47.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.027 seconds
[2025-01-22T09:00:17.689+0000] {processor.py:186} INFO - Started process (PID=674) to work on /opt/airflow/dags/b.py
[2025-01-22T09:00:17.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:00:17.691+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:00:17.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:00:17.703+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:00:17.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:00:17.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:00:17.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.033 seconds
[2025-01-22T09:00:48.328+0000] {processor.py:186} INFO - Started process (PID=686) to work on /opt/airflow/dags/b.py
[2025-01-22T09:00:48.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:00:48.331+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:00:48.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:00:48.338+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:00:48.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:00:48.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:00:48.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.030 seconds
[2025-01-22T09:01:19.040+0000] {processor.py:186} INFO - Started process (PID=699) to work on /opt/airflow/dags/b.py
[2025-01-22T09:01:19.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:01:19.043+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:01:19.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:01:19.052+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:01:19.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:01:19.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:01:19.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.029 seconds
[2025-01-22T09:01:49.659+0000] {processor.py:186} INFO - Started process (PID=711) to work on /opt/airflow/dags/b.py
[2025-01-22T09:01:49.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:01:49.661+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:01:49.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:01:49.669+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:01:49.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:01:49.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:01:49.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.031 seconds
[2025-01-22T09:02:20.319+0000] {processor.py:186} INFO - Started process (PID=723) to work on /opt/airflow/dags/b.py
[2025-01-22T09:02:20.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:02:20.321+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:02:20.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:02:20.339+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:02:20.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:02:20.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:02:20.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.037 seconds
[2025-01-22T09:02:51.018+0000] {processor.py:186} INFO - Started process (PID=735) to work on /opt/airflow/dags/b.py
[2025-01-22T09:02:51.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:02:51.021+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:02:51.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:02:51.035+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:02:51.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:02:51.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:02:51.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.033 seconds
[2025-01-22T09:03:21.943+0000] {processor.py:186} INFO - Started process (PID=747) to work on /opt/airflow/dags/b.py
[2025-01-22T09:03:21.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:03:21.946+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:03:21.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:03:21.967+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:03:21.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:03:21.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:03:21.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.045 seconds
[2025-01-22T09:03:52.092+0000] {processor.py:186} INFO - Started process (PID=759) to work on /opt/airflow/dags/b.py
[2025-01-22T09:03:52.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:03:52.096+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:03:52.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:03:52.203+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:03:52.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:03:52.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:03:52.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.129 seconds
[2025-01-22T09:04:22.664+0000] {processor.py:186} INFO - Started process (PID=771) to work on /opt/airflow/dags/b.py
[2025-01-22T09:04:22.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:04:22.669+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:04:22.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:04:22.772+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:04:22.771+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:04:22.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:04:22.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.136 seconds
[2025-01-22T09:04:53.798+0000] {processor.py:186} INFO - Started process (PID=783) to work on /opt/airflow/dags/b.py
[2025-01-22T09:04:53.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:04:53.802+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:04:53.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:04:53.882+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:04:53.881+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:04:53.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:04:53.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.110 seconds
[2025-01-22T09:05:24.220+0000] {processor.py:186} INFO - Started process (PID=795) to work on /opt/airflow/dags/b.py
[2025-01-22T09:05:24.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:05:24.224+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:05:24.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:05:24.299+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:05:24.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:05:24.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:05:24.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.102 seconds
[2025-01-22T09:05:54.959+0000] {processor.py:186} INFO - Started process (PID=807) to work on /opt/airflow/dags/b.py
[2025-01-22T09:05:54.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:05:54.962+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:05:54.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:05:54.969+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:05:54.968+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:05:54.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:05:54.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.026 seconds
[2025-01-22T09:06:25.538+0000] {processor.py:186} INFO - Started process (PID=819) to work on /opt/airflow/dags/b.py
[2025-01-22T09:06:25.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:06:25.541+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:06:25.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:06:25.552+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:06:25.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:06:25.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:06:25.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.031 seconds
[2025-01-22T09:06:55.996+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/b.py
[2025-01-22T09:06:55.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:06:55.999+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:06:55.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:06:56.013+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:06:56.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:06:56.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:06:56.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.035 seconds
[2025-01-22T09:07:26.408+0000] {processor.py:186} INFO - Started process (PID=843) to work on /opt/airflow/dags/b.py
[2025-01-22T09:07:26.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:07:26.410+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:07:26.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:07:26.425+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:07:26.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:07:26.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:07:26.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.034 seconds
[2025-01-22T09:07:56.856+0000] {processor.py:186} INFO - Started process (PID=855) to work on /opt/airflow/dags/b.py
[2025-01-22T09:07:56.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:07:56.859+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:07:56.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:07:56.866+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:07:56.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:07:56.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:07:56.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.028 seconds
[2025-01-22T09:08:27.367+0000] {processor.py:186} INFO - Started process (PID=867) to work on /opt/airflow/dags/b.py
[2025-01-22T09:08:27.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:08:27.370+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:08:27.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:08:27.380+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:08:27.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:08:27.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:08:27.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.031 seconds
[2025-01-22T09:08:57.873+0000] {processor.py:186} INFO - Started process (PID=879) to work on /opt/airflow/dags/b.py
[2025-01-22T09:08:57.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:08:57.876+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:08:57.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:08:57.894+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:08:57.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:08:57.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:08:57.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.043 seconds
[2025-01-22T09:09:28.318+0000] {processor.py:186} INFO - Started process (PID=892) to work on /opt/airflow/dags/b.py
[2025-01-22T09:09:28.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:09:28.320+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:09:28.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:09:28.328+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:09:28.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:09:28.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:09:28.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.031 seconds
[2025-01-22T09:09:58.763+0000] {processor.py:186} INFO - Started process (PID=904) to work on /opt/airflow/dags/b.py
[2025-01-22T09:09:58.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:09:58.766+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:09:58.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:09:58.780+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:09:58.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 10
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:09:58.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:09:58.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.035 seconds
[2025-01-22T09:10:26.229+0000] {processor.py:186} INFO - Started process (PID=916) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:26.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:26.231+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:26.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:26.238+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:26.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 11
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:10:26.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:26.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.030 seconds
[2025-01-22T09:10:27.319+0000] {processor.py:186} INFO - Started process (PID=917) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:27.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:27.323+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:27.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:27.349+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:27.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 11
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:10:27.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:27.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.049 seconds
[2025-01-22T09:10:29.370+0000] {processor.py:186} INFO - Started process (PID=918) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:29.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:29.373+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:29.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:29.394+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:29.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 11
    )
     ^
SyntaxError: expected ':'
[2025-01-22T09:10:29.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:29.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.043 seconds
[2025-01-22T09:10:35.516+0000] {processor.py:186} INFO - Started process (PID=926) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:35.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:35.518+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:35.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:35.532+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:35.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 12
    
    ^
IndentationError: expected an indented block after 'with' statement on line 7
[2025-01-22T09:10:35.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:35.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.035 seconds
[2025-01-22T09:10:37.857+0000] {processor.py:186} INFO - Started process (PID=931) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:37.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:37.860+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:37.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:37.872+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:37.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 12
    task1=
          ^
SyntaxError: invalid syntax
[2025-01-22T09:10:37.872+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:37.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.033 seconds
[2025-01-22T09:10:43.938+0000] {processor.py:186} INFO - Started process (PID=932) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:43.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:43.940+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:43.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:43.968+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:43.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:10:43.970+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:43.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.051 seconds
[2025-01-22T09:10:47.012+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:47.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:47.014+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:47.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:47.040+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:47.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:10:47.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:47.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.045 seconds
[2025-01-22T09:10:51.090+0000] {processor.py:186} INFO - Started process (PID=934) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:51.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:51.093+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:51.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:51.116+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:51.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:10:51.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:51.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.046 seconds
[2025-01-22T09:10:53.160+0000] {processor.py:186} INFO - Started process (PID=935) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:53.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:53.163+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:53.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:53.189+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:53.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:10:53.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:53.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.052 seconds
[2025-01-22T09:10:57.240+0000] {processor.py:186} INFO - Started process (PID=936) to work on /opt/airflow/dags/b.py
[2025-01-22T09:10:57.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:10:57.243+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:57.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:10:57.250+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:10:57.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 15
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-22T09:10:57.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:10:57.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.031 seconds
[2025-01-22T09:11:01.300+0000] {processor.py:186} INFO - Started process (PID=943) to work on /opt/airflow/dags/b.py
[2025-01-22T09:11:01.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:11:01.303+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:01.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:11:01.319+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:01.318+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 15
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-22T09:11:01.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:11:01.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.037 seconds
[2025-01-22T09:11:03.337+0000] {processor.py:186} INFO - Started process (PID=944) to work on /opt/airflow/dags/b.py
[2025-01-22T09:11:03.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:11:03.340+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:03.340+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:11:03.354+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:03.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 14
    python_callable=
    ^^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-01-22T09:11:03.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:11:03.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.038 seconds
[2025-01-22T09:11:14.078+0000] {processor.py:186} INFO - Started process (PID=950) to work on /opt/airflow/dags/b.py
[2025-01-22T09:11:14.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:11:14.081+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:14.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:11:14.101+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:14.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 15
    python_callable=
    ^^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-01-22T09:11:14.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:11:14.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.039 seconds
[2025-01-22T09:11:44.487+0000] {processor.py:186} INFO - Started process (PID=960) to work on /opt/airflow/dags/b.py
[2025-01-22T09:11:44.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:11:44.490+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:44.490+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:11:44.504+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:44.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 15
    python_callable=
    ^^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-01-22T09:11:44.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:11:44.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.036 seconds
[2025-01-22T09:11:56.624+0000] {processor.py:186} INFO - Started process (PID=961) to work on /opt/airflow/dags/b.py
[2025-01-22T09:11:56.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:11:56.626+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:56.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:11:56.643+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:11:56.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:11:56.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:11:56.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.039 seconds
[2025-01-22T09:12:01.697+0000] {processor.py:186} INFO - Started process (PID=968) to work on /opt/airflow/dags/b.py
[2025-01-22T09:12:01.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:12:01.700+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:01.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:12:01.727+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:01.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:12:01.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:12:01.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.050 seconds
[2025-01-22T09:12:10.141+0000] {processor.py:186} INFO - Started process (PID=974) to work on /opt/airflow/dags/b.py
[2025-01-22T09:12:10.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:12:10.144+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:10.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:12:10.169+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:10.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:12:10.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:12:10.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.047 seconds
[2025-01-22T09:12:11.148+0000] {processor.py:186} INFO - Started process (PID=975) to work on /opt/airflow/dags/b.py
[2025-01-22T09:12:11.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:12:11.151+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:11.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:12:11.165+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:11.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:12:11.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:12:11.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.037 seconds
[2025-01-22T09:12:41.527+0000] {processor.py:186} INFO - Started process (PID=987) to work on /opt/airflow/dags/b.py
[2025-01-22T09:12:41.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:12:41.530+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:41.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:12:41.549+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:41.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 3, in <module>
    from airflow.operators.python import PyhtonOperator,BranchPythonOperator
ImportError: cannot import name 'PyhtonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-01-22T09:12:41.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:12:41.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.045 seconds
[2025-01-22T09:12:51.664+0000] {processor.py:186} INFO - Started process (PID=988) to work on /opt/airflow/dags/b.py
[2025-01-22T09:12:51.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:12:51.668+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:51.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:12:51.701+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:51.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 13, in <module>
    task1=PyhtonOperator(
          ^^^^^^^^^^^^^^
NameError: name 'PyhtonOperator' is not defined. Did you mean: 'PythonOperator'?
[2025-01-22T09:12:51.702+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:12:51.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.056 seconds
[2025-01-22T09:12:53.768+0000] {processor.py:186} INFO - Started process (PID=989) to work on /opt/airflow/dags/b.py
[2025-01-22T09:12:53.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:12:53.771+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:12:53.809+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:12:53.928+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.927+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:branching_2
[2025-01-22T09:12:53.938+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.937+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:branching_2
[2025-01-22T09:12:53.947+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.947+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:branching_2
[2025-01-22T09:12:53.955+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.955+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:branching_2
[2025-01-22T09:12:53.961+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.961+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:branching_2
[2025-01-22T09:12:53.967+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.967+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:branching_2
[2025-01-22T09:12:53.973+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.973+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:branching_2
[2025-01-22T09:12:53.974+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.974+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:12:53.983+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.983+0000] {dag.py:3262} INFO - Creating ORM DAG for branching_2
[2025-01-22T09:12:53.989+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:53.989+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to 2025-01-22 00:00:00+00:00, run_after=2025-01-22 00:00:00+00:00
[2025-01-22T09:12:54.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.247 seconds
[2025-01-22T09:12:54.795+0000] {processor.py:186} INFO - Started process (PID=990) to work on /opt/airflow/dags/b.py
[2025-01-22T09:12:54.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:12:54.797+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:54.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:12:54.826+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:12:54.833+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:54.833+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:12:54.848+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:12:54.848+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to 2025-01-22 00:00:00+00:00, run_after=2025-01-22 00:00:00+00:00
[2025-01-22T09:12:54.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.075 seconds
[2025-01-22T09:13:25.239+0000] {processor.py:186} INFO - Started process (PID=1002) to work on /opt/airflow/dags/b.py
[2025-01-22T09:13:25.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:13:25.242+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:13:25.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:13:25.254+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:13:25.268+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:13:25.268+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:13:25.282+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:13:25.282+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:13:25.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.058 seconds
[2025-01-22T09:13:55.709+0000] {processor.py:186} INFO - Started process (PID=1013) to work on /opt/airflow/dags/b.py
[2025-01-22T09:13:55.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:13:55.711+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:13:55.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:13:55.769+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:13:55.785+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:13:55.785+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:13:55.799+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:13:55.799+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:13:55.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.110 seconds
[2025-01-22T09:14:26.171+0000] {processor.py:186} INFO - Started process (PID=1025) to work on /opt/airflow/dags/b.py
[2025-01-22T09:14:26.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:14:26.174+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:14:26.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:14:26.190+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:14:26.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 4, in <module>
    from functions import *
  File "/opt/airflow/dags/functions.py", line 42
    if ti=ti.xcom_pull(task_ids="check_driving_licence")
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
[2025-01-22T09:14:26.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:14:26.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.041 seconds
[2025-01-22T09:14:57.121+0000] {processor.py:186} INFO - Started process (PID=1037) to work on /opt/airflow/dags/b.py
[2025-01-22T09:14:57.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:14:57.123+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:14:57.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:14:57.153+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:14:57.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 4, in <module>
    from functions import *
  File "/opt/airflow/dags/functions.py", line 45
    return 'cantt drive
           ^
SyntaxError: unterminated string literal (detected at line 45)
[2025-01-22T09:14:57.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:14:57.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.050 seconds
[2025-01-22T09:15:10.331+0000] {processor.py:186} INFO - Started process (PID=1044) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:10.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:10.335+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:10.335+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:10.344+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:10.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 17
    task2=
          ^
SyntaxError: invalid syntax
[2025-01-22T09:15:10.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:10.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.032 seconds
[2025-01-22T09:15:11.397+0000] {processor.py:186} INFO - Started process (PID=1046) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:11.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:11.400+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:11.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:11.430+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:11.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 17, in <module>
    task2=Br
          ^^
NameError: name 'Br' is not defined
[2025-01-22T09:15:11.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:11.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.051 seconds
[2025-01-22T09:15:12.722+0000] {processor.py:186} INFO - Started process (PID=1051) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:12.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:12.724+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:12.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:12.751+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:12.765+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:12.765+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:15:12.779+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:12.779+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:15:12.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.085 seconds
[2025-01-22T09:15:14.754+0000] {processor.py:186} INFO - Started process (PID=1052) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:14.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:14.757+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:14.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:14.781+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:14.796+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:14.796+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:15:14.809+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:14.809+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:15:14.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.077 seconds
[2025-01-22T09:15:19.818+0000] {processor.py:186} INFO - Started process (PID=1053) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:19.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:19.821+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:19.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:19.849+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:19.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 17, in <module>
    task2=BranchPythonOperator(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-22T09:15:19.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:19.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.049 seconds
[2025-01-22T09:15:27.912+0000] {processor.py:186} INFO - Started process (PID=1054) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:27.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:27.915+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:27.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:27.945+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:27.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 17, in <module>
    task2=BranchPythonOperator(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-22T09:15:27.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:27.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.053 seconds
[2025-01-22T09:15:32.055+0000] {processor.py:186} INFO - Started process (PID=1061) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:32.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:32.058+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:32.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:32.097+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:32.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 17, in <module>
    task2=BranchPythonOperator(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-22T09:15:32.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:32.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.059 seconds
[2025-01-22T09:15:34.098+0000] {processor.py:186} INFO - Started process (PID=1062) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:34.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:34.101+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:34.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:34.129+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:34.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 17, in <module>
    task2=BranchPythonOperator(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-22T09:15:34.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:34.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.050 seconds
[2025-01-22T09:15:45.620+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:45.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:45.624+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:45.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:45.641+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:45.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 20
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-22T09:15:45.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:45.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.040 seconds
[2025-01-22T09:15:46.634+0000] {processor.py:186} INFO - Started process (PID=1069) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:46.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:46.637+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:46.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:46.658+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:46.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 19
    python_callable=
    ^^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-01-22T09:15:46.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:46.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.043 seconds
[2025-01-22T09:15:53.711+0000] {processor.py:186} INFO - Started process (PID=1070) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:53.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:53.714+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:53.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:53.739+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:53.825+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:53.825+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:15:53.837+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:53.837+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:15:53.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.151 seconds
[2025-01-22T09:15:54.790+0000] {processor.py:186} INFO - Started process (PID=1071) to work on /opt/airflow/dags/b.py
[2025-01-22T09:15:54.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:15:54.793+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:54.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:15:54.823+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:15:54.830+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:54.830+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:15:54.845+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:15:54.845+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:15:54.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.078 seconds
[2025-01-22T09:16:25.343+0000] {processor.py:186} INFO - Started process (PID=1083) to work on /opt/airflow/dags/b.py
[2025-01-22T09:16:25.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:16:25.347+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:25.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:16:25.427+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:16:25.442+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:25.442+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:16:25.456+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:25.456+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:16:25.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.135 seconds
[2025-01-22T09:16:35.452+0000] {processor.py:186} INFO - Started process (PID=1090) to work on /opt/airflow/dags/b.py
[2025-01-22T09:16:35.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:16:35.455+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:35.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:16:35.474+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:35.474+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 21
    task1=PythonOperator(
IndentationError: unexpected indent
[2025-01-22T09:16:35.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:16:35.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.042 seconds
[2025-01-22T09:16:37.486+0000] {processor.py:186} INFO - Started process (PID=1091) to work on /opt/airflow/dags/b.py
[2025-01-22T09:16:37.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:16:37.489+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:37.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:16:37.542+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:37.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 21, in <module>
    task1=PythonOperator(
          ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 975, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/task_group.py", line 256, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'check_driving_licence' has already been added to the DAG
[2025-01-22T09:16:37.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:16:37.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.073 seconds
[2025-01-22T09:16:40.582+0000] {processor.py:186} INFO - Started process (PID=1092) to work on /opt/airflow/dags/b.py
[2025-01-22T09:16:40.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:16:40.585+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:40.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:16:40.646+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:40.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 21, in <module>
    task3=PythonOperator(
          ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 975, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/task_group.py", line 256, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'check_driving_licence' has already been added to the DAG
[2025-01-22T09:16:40.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:16:40.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.083 seconds
[2025-01-22T09:16:49.822+0000] {processor.py:186} INFO - Started process (PID=1098) to work on /opt/airflow/dags/b.py
[2025-01-22T09:16:49.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:16:49.825+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:49.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:16:49.854+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:16:49.920+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:49.920+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:16:49.932+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:49.931+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:16:49.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.136 seconds
[2025-01-22T09:16:55.920+0000] {processor.py:186} INFO - Started process (PID=1099) to work on /opt/airflow/dags/b.py
[2025-01-22T09:16:55.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:16:55.923+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:55.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:16:55.954+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:16:55.961+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:55.961+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:16:55.974+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:55.974+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:16:55.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.080 seconds
[2025-01-22T09:16:59.977+0000] {processor.py:186} INFO - Started process (PID=1100) to work on /opt/airflow/dags/b.py
[2025-01-22T09:16:59.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:16:59.979+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:59.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:16:59.995+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:16:59.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 25
    task3=PythonOperator(
IndentationError: unexpected indent
[2025-01-22T09:16:59.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:17:00.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.039 seconds
[2025-01-22T09:17:03.007+0000] {processor.py:186} INFO - Started process (PID=1107) to work on /opt/airflow/dags/b.py
[2025-01-22T09:17:03.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:17:03.010+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:03.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:17:03.043+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:03.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 25, in <module>
    task3=PythonOperator(
          ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 975, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/task_group.py", line 256, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'can_drive' has already been added to the DAG
[2025-01-22T09:17:03.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:17:03.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.056 seconds
[2025-01-22T09:17:05.103+0000] {processor.py:186} INFO - Started process (PID=1108) to work on /opt/airflow/dags/b.py
[2025-01-22T09:17:05.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:17:05.105+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:05.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:17:05.134+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:05.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 25, in <module>
    task4=PythonOperator(
          ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 975, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/task_group.py", line 256, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'can_drive' has already been added to the DAG
[2025-01-22T09:17:05.135+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:17:05.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.050 seconds
[2025-01-22T09:17:09.172+0000] {processor.py:186} INFO - Started process (PID=1109) to work on /opt/airflow/dags/b.py
[2025-01-22T09:17:09.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:17:09.174+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:09.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:17:09.207+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:17:09.213+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:09.213+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:17:09.227+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:09.226+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:17:09.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.083 seconds
[2025-01-22T09:17:15.348+0000] {processor.py:186} INFO - Started process (PID=1111) to work on /opt/airflow/dags/b.py
[2025-01-22T09:17:15.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:17:15.351+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:15.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:17:15.380+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:17:15.386+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:15.386+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:17:15.401+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:15.401+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:17:15.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.083 seconds
[2025-01-22T09:17:45.954+0000] {processor.py:186} INFO - Started process (PID=1123) to work on /opt/airflow/dags/b.py
[2025-01-22T09:17:45.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:17:45.957+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:45.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:17:45.986+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:17:46.053+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:46.052+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:17:46.066+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:46.066+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:17:46.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.133 seconds
[2025-01-22T09:17:49.405+0000] {processor.py:186} INFO - Started process (PID=1128) to work on /opt/airflow/dags/b.py
[2025-01-22T09:17:49.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:17:49.408+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:49.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:17:49.431+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:17:49.437+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:49.437+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:17:49.451+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:49.451+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:17:49.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.069 seconds
[2025-01-22T09:17:55.480+0000] {processor.py:186} INFO - Started process (PID=1129) to work on /opt/airflow/dags/b.py
[2025-01-22T09:17:55.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:17:55.482+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:55.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:17:55.497+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:17:55.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 29
    task1>>task2>>
                  ^
SyntaxError: invalid syntax
[2025-01-22T09:17:55.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:17:55.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.036 seconds
[2025-01-22T09:18:00.556+0000] {processor.py:186} INFO - Started process (PID=1130) to work on /opt/airflow/dags/b.py
[2025-01-22T09:18:00.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:18:00.560+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:00.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:18:00.620+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:18:00.627+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:00.627+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:18:00.641+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:00.641+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:18:00.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.111 seconds
[2025-01-22T09:18:02.616+0000] {processor.py:186} INFO - Started process (PID=1137) to work on /opt/airflow/dags/b.py
[2025-01-22T09:18:02.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:18:02.619+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:02.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:18:02.653+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:18:02.661+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:02.661+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:18:02.678+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:02.678+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:18:02.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.089 seconds
[2025-01-22T09:18:33.050+0000] {processor.py:186} INFO - Started process (PID=1155) to work on /opt/airflow/dags/b.py
[2025-01-22T09:18:33.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:18:33.055+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:33.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:18:33.072+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:18:33.133+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:33.133+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:18:33.144+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:18:33.144+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:18:33.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.109 seconds
[2025-01-22T09:19:03.569+0000] {processor.py:186} INFO - Started process (PID=1167) to work on /opt/airflow/dags/b.py
[2025-01-22T09:19:03.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:19:03.571+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:19:03.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:19:03.588+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:19:03.604+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:19:03.603+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:19:03.618+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:19:03.618+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:19:03.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.065 seconds
[2025-01-22T09:19:33.939+0000] {processor.py:186} INFO - Started process (PID=1179) to work on /opt/airflow/dags/b.py
[2025-01-22T09:19:33.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:19:33.942+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:19:33.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:19:33.954+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:19:33.968+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:19:33.968+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:19:33.981+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:19:33.981+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:19:34.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.065 seconds
[2025-01-22T09:20:04.568+0000] {processor.py:186} INFO - Started process (PID=1191) to work on /opt/airflow/dags/b.py
[2025-01-22T09:20:04.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:20:04.570+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:20:04.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:20:04.587+0000] {processor.py:925} INFO - DAG(s) 'branching_2' retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:20:04.600+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:20:04.600+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-22T09:20:04.612+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:20:04.612+0000] {dag.py:4180} INFO - Setting next_dagrun for branching_2 to None, run_after=None
[2025-01-22T09:20:04.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.065 seconds
[2025-01-22T09:20:35.035+0000] {processor.py:186} INFO - Started process (PID=1203) to work on /opt/airflow/dags/b.py
[2025-01-22T09:20:35.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:20:35.038+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:20:35.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:20:35.076+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:20:35.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 15, in <module>
    python_callable=has_driving_licence
                    ^^^^^^^^^^^^^^^^^^^
NameError: name 'has_driving_licence' is not defined
[2025-01-22T09:20:35.079+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:20:35.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.066 seconds
[2025-01-22T09:21:05.542+0000] {processor.py:186} INFO - Started process (PID=1215) to work on /opt/airflow/dags/b.py
[2025-01-22T09:21:05.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/b.py for tasks to queue
[2025-01-22T09:21:05.545+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:21:05.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/b.py
[2025-01-22T09:21:05.558+0000] {logging_mixin.py:190} INFO - [2025-01-22T09:21:05.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/b.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/b.py", line 15, in <module>
    python_callable=has_driving_licence
                    ^^^^^^^^^^^^^^^^^^^
NameError: name 'has_driving_licence' is not defined
[2025-01-22T09:21:05.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/b.py
[2025-01-22T09:21:05.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/b.py took 0.036 seconds
