[2025-01-22T09:19:54.942+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T09:19:54.955+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branching_2.cant_drive manual__2025-01-22T09:19:52.566961+00:00 [queued]>
[2025-01-22T09:19:54.961+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branching_2.cant_drive manual__2025-01-22T09:19:52.566961+00:00 [queued]>
[2025-01-22T09:19:54.961+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-22T09:19:54.970+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): cant_drive> on 2025-01-22 09:19:52.566961+00:00
[2025-01-22T09:19:54.974+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=794) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-22T09:19:54.976+0000] {standard_task_runner.py:72} INFO - Started process 795 to run task
[2025-01-22T09:19:54.976+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branching_2', 'cant_drive', 'manual__2025-01-22T09:19:52.566961+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/b.py', '--cfg-path', '/tmp/tmps7pab_11']
[2025-01-22T09:19:54.977+0000] {standard_task_runner.py:105} INFO - Job 211: Subtask cant_drive
[2025-01-22T09:19:55.003+0000] {task_command.py:467} INFO - Running <TaskInstance: branching_2.cant_drive manual__2025-01-22T09:19:52.566961+00:00 [running]> on host 7854821b9569
[2025-01-22T09:19:55.049+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branching_2' AIRFLOW_CTX_TASK_ID='cant_drive' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T09:19:52.566961+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T09:19:52.566961+00:00'
[2025-01-22T09:19:55.050+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T09:19:55.058+0000] {logging_mixin.py:190} INFO - you cant drive !
[2025-01-22T09:19:55.058+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-22T09:19:55.064+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T09:19:55.064+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=branching_2, task_id=cant_drive, run_id=manual__2025-01-22T09:19:52.566961+00:00, execution_date=20250122T091952, start_date=20250122T091954, end_date=20250122T091955
[2025-01-22T09:19:55.110+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T09:19:55.122+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-22T09:19:55.125+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
